---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: k3s-deployment
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/yochanan2007/k3s-deployment
  ref:
    branch: main
